### PR TITLE
fix: Add more space to columns that are potential to larger data

### LINKED ISSUE #13: String data, right truncated: Data too long for column 'id'
Another case of too narrow columns for data that keeps expanding in size:

```
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'id' at row 1 (Connection: mysql, SQL: insert into `ruter_transactions` (`amount`, `app_instance_id`, `app_instance_name`, `chunk_date`, `credit_amount`, `credit_date`, `cs_comment`, `cs_invoice_ref`, `cs_ordered_by`, `distribution_type`, `id`, `order_date`, `order_id`, `order_status`, `owner`, `payer_app_instance_name`, `payer_app_platform`, `payer_app_version`, `payer_id`, `payer_os_version`, `payer_phone_type`, `payment_id`, `payment_method`, `payment_status`, `stop_from`, `stop_to`, `ticket_number`, `ticket_status`, `ticket_type`, `ticket_type_id`, `transaction_type`, `valid_from`, `valid_to`, `vat_amount`, `vat_percentage`, `zone_from`, `zone_to`, `zones`, `zones_all`) values (***, ?, ?, 2024-08-22 00:00:00, ***, 2024-08-22 10:30:01, ?, ?, ?, PREPURCHASE, *************************************************************************************************, ...
```

## Suggested resolution
Widen all char and integer columns

### PR DESCRIPTION
**Pull request by tfk-kaare**

### CODE REVIEW

File: database/migrations/2024_08_23_140000_ragnarok_ruter_widen_columns.php [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+return new class extends Migration
+{
+    /**
+     * Run the migrations.
+     */
+    public function up(): void
+    {
+        Schema::table('ruter_transactions', function(Blueprint $table) {
+            $table->char('id')->comment('Transaction ID in UUID-ish format with appended string.')->change();
```
Comment (imable) [inline database/migrations/2024_08_23_140000_ragnarok_ruter_widen_columns.php:15]: Not my area of expertise this. Do I understand it correctly that we created a new table somewhere with a larger `id` size and this script is just copying values over?

Comment (tfk-kaare) [reply database/migrations/2024_08_23_140000_ragnarok_ruter_widen_columns.php:15]: No, the `->change()` will change the schema definition to existing columns, based on the chained set of commands to Schema::table. Alter table, that is.

**Review by tft-kyrre — APPROVED** [review]
